### ISSUE TITLE
Youtube Chat No Longer Displays Emotes/Images When Chat Translator Is Active

### ISSUE THREAD

**Issue by ghost** [T3aHat/Chat_Translator_for_DeepL#1]
If a commentator in the chat is a Member of a Youtube channel and uses their channel-specific emote, DeepL will fail to parse that chat comment (because it's actually an image in the chat and not text?) and leave it empty.

**Comment by T3aHat** [comment]
textContextを変更していたが、画像等も残すためにtag_handlingでの書き換えを検討したい。  
I had changed `textContext`, but I would like to consider the implementation with tag_handling to keep images, etc.

**Comment by T3aHat** [comment]
tag_handling:"xml"で対応
